"""empty message

Revision ID: 311f72f3a6b1
Revises: 9ed83db34ed1
Create Date: 2022-03-18 17:57:30.180569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311f72f3a6b1'
down_revision = '9ed83db34ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
